name: "Code Quality Check"

on:
  pull_request:
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/code_quality.yml"

jobs:
  phpcs:
    name: "PHP CodeSniffer"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.3', '7.4', '8.0', '8.1', '8.2']
    steps:
      - name: Check out code into the workspace
        uses: actions/checkout@v2
      - name: Run PHPCS
        uses: chekalsky/phpcs-action@v1
  phpmd:
    name: "PHP MessDetector"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.3', '7.4', '8.0', '8.1', '8.2']
    steps:
      - name: Check out code into the workspace
        uses: actions/checkout@v2
      - name: Run PHPMD
        uses: GeneaLabs/action-reviewdog-phpmd@1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: 'warning'
          reporter: github-pr-check
          standard: './phpmd.xml.dist'
          target_directory: 'src'
  phpstan:
    name: PHPStan
<<<<<<< HEAD
<<<<<<< HEAD
    runs-on: ubuntu-latest
=======
    runs-on: ubuntu-18.04
>>>>>>> b302de1 (shate matrix for code quality tools)
=======
    runs-on: ubuntu-latest
>>>>>>> 1ae9e62 (update phpstan action)
    strategy:
      matrix:
        php-version: ['7.3', '7.4', '8.0', '8.1', '8.2']
    steps:
      - name: Check out code into the workspace
        uses: actions/checkout@v2
      - name: Run PHPStan
        uses: php-actions/phpstan@v3
        with:
<<<<<<< HEAD
          args: analyse src -c phpstan.neon --memory-limit=1G --no-progress
=======
          configuration: ./phpstan.neon
>>>>>>> 1ae9e62 (update phpstan action)

